#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Carol Bogezi, PhD

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.carolbogezi.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "" #/researcher


# permalink: /:title/

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Based on Researcher template by Ankit Sultana"

# added from barryclark repo _config.yml file
# Includes an icon in the footer for each username you enter
# footer-links:
#   email: cbogezi@gmail.com
#   github: cbogezi
#   instagram:
#   linkedin:
#   rss: # just type anything here for a working RSS icon
#   twitter: carolwildlife


# remote_theme: ankitsultana/researcher@gh-pages

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index" #index
 - name: "Resume"
   link: "resume.pdf"
 - name: "Talks"
   link: "talks"
 - name: "Contact"
   link: "contact"
 # - name: "Resume"
 #   link: "resume.pdf" # put your files in the assets directory
 # - name: "About"
 #   link: "/researcher/"
